#! /bin/bash
#
# Usage:
#  build [OS...]
#
# Parameters:
#  OS  an operating system to build the package for: centos6 or centos7
#
# Builds the iRODS msiSetAVU plugin packages. It writes each package into an OS
# specific subdirectory of libraries/.
#

readonly AllOSes=(centos6 centos7)


main()
{
  local oses=("$@")

  if [ ${#oses} -eq 0 ]
  then
    oses=(${AllOSes[*]})
  else
    for candidateOS in ${oses[*]}
    do
      local verified=false

      for os in ${AllOSes[*]}
      do
        if [ "$candidateOS" = "$os" ]
        then
          verified=true
          break
        fi
      done

      if [ "$verified" = false ]
      then
        printf 'The OS %s is unsupported\n' "$candidateOS" >&2
        return 1
      fi
    done
  fi

  local baseDir=$(dirname $(readlink --canonicalize "$0"))

  for os in ${oses[*]}
  do
    docker build --file "$baseDir"/dockerfiles/Dockerfile."$os" --tag irods-dev-build:4.1.10-"$os" \
                 "$baseDir"

    local library="$baseDir"/libraries/"$os"
    local scratch="$baseDir"/scratch/"$os"

    mkdir --parents "$library" "$scratch"
    cp --update "$baseDir"/src/* "$scratch"

    docker run --rm --tty --user=$(id -u):$(id -g) --volume="$scratch":/src --name=setavu-builder \
	             irods-dev-build:4.1.10-"$os" make all

    cp --update "$scratch"/libmsiSetAVU.so "$library"
  done
}


set -e

main "$@"
